More extensive publishing CI

diff --git a/.github/workflows/pythonpublish.yaml b/.github/workflows/pythonpublish.yaml
--- a/.github/workflows/pythonpublish.yaml
+++ b/.github/workflows/pythonpublish.yaml
@@ -1,26 +1,104 @@
-name: Upload Python Package
-
+name: Build and Upload xarrayutils to PyPI
 on:
   release:
-    types: [created]
+    types:
+      - published
+  push:
+    tags:
+      - 'v*rc*' # only trigger this for dev releases (which I currently call release candidates...
 
 jobs:
-  deploy:
+  build-artifacts:
     runs-on: ubuntu-latest
+    if: github.repository == 'jbusecke/xarrayutils'
     steps:
-      - uses: actions/checkout@v1
-      - name: Set up Python
-        uses: actions/setup-python@v1
+      - uses: actions/checkout@v2
         with:
-          python-version: '3.x'
+          fetch-depth: 0
+      - uses: actions/setup-python@v2
+        name: Install Python
+        with:
+          python-version: 3.8
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install setuptools setuptools-scm wheel twine
-      - name: Build and publish
-        env:
-          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
-          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+          python -m pip install setuptools setuptools-scm[toml] wheel twine
+      - name: Check python version
         run: |
+          python --version
+      - name: Check current package version
+        run: |
+          python setup.py --version
+      - name: Build tarball and wheels
+        run: |
+          git clean -xdf
+          git restore -SW .
           python setup.py sdist bdist_wheel
-          twine upload dist/*
+      - name: Check built artifacts
+        run: |
+          python -m twine check dist/*
+          pwd
+          if [ -f dist/xarrayutils-0.0.0.tar.gz ]; then
+            echo "❌ INVALID VERSION NUMBER"
+            exit 1
+          else
+            echo "✅ Looks good"
+          fi
+      - uses: actions/upload-artifact@v2
+        with:
+          name: releases
+          path: dist
+
+  test-built-dist:
+    needs: build-artifacts
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/setup-python@v2
+        name: Install Python
+        with:
+          python-version: 3.8
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
+      - name: List contents of built dist
+        run: |
+          ls -ltrh
+          ls -ltrh dist
+      - name: Publish package to TestPyPI
+        uses: pypa/gh-action-pypi-publish@v1.4.2
+        with:
+          user: __token__
+          password: ${{ secrets.TESTPYPI_TOKEN }}
+          repository_url: https://test.pypi.org/legacy/
+          verbose: true
+      # - name: Setup upterm session
+      #   uses: lhotari/action-upterm@v1
+      - name: Check uploaded package
+        run: |
+          sleep 10
+          python -m pip install --upgrade pip
+          pip cache purge
+          # This is kind of stupid, but the only way I got this to work with the latest versions on testpypi
+          # If I used: python -m pip install --extra-index-url https://test.pypi.org/simple --upgrade xarrayutils
+          # It would grab an older cmip6_pp version and with `--index-url=...` I cant get the proper dependencies from pypi
+          # So I am installing the dependencies manually from pypi and the newest version from testpypi...not sure if this
+          # defeats the purpose, but I am frankly fed up with this shit!
+          python -m pip install xgcm xarray numpy pandas cftime
+          python -m pip install --index-url https://test.pypi.org/simple --upgrade xarrayutils
+          python -c "import xarrayutils;print(xarrayutils.__version__)"
+  upload-to-pypi:
+    needs: test-built-dist
+    if: github.event_name == 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
+      - name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@v1.4.2
+        with:
+          user: __token__
+          password: ${{ secrets.PYPI_TOKEN }}
+          verbose: true
